### ISSUE TITLE
Serverless & RPC example broken

### ISSUE THREAD

**Issue by SampsonCrowley** [hyperstack-org/website#32]
3 Issues in the log:

1) getDefault props should be `defaultProps`

2) There's an array without `key` props

3) the FaaStRuby example does nothing visible when clicked. It is erroring out behind the scenes, but the error is just being swallowed with nothing visible to the user to know that the button is even clicked

```
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
i @ application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98 Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in div
    in t (created by LiveCodeSegment)
    in div
    in Ki (created by LiveCodeSegment)
    in div
    in gi (created by LiveCodeSegment)
    in div
    in ki (created by LiveCodeSegment)
    in div (created by LiveCodeSegment)
    in LiveCodeSegment (created by HomePage)
    in div
    in Ki (created by HomePage)
    in div
    in Ki (created by HomePage)
    in div (created by HomePage)
    in HomePage (created by $)
    in $ (created by n)
    in n (created by AppRouter)
    in n (created by AppRouter)
    in n (created by AppRouter)
    in AppRouter (created by Hyperstack::Internal::Component::TopLevelRailsComponent)
    in Hyperstack::Internal::Component::TopLevelRailsComponent
i @ application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
i @ application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
i @ application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
i @ application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98 Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
i @ application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:98
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:30 Uncaught nmessage: "Unexpected token H in JSON at position 0"name: "ParserError"stack: "ParserError: Unexpected token H in JSON at position 0↵    at l (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:261:10302)↵    at n._ [as $parse] (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:261:11674)↵    at $.f [as $json] (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:267:6148)↵    at TMP_7 (eval at $$evaluate (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:293:28387), <anonymous>:43:63)↵    at Object.y.yieldX (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:29:1176)↵    at Function.c [as $call] (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:36:832)↵    at $.g [as $succeed] (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:267:7028)↵    at Object.$.success (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:267:5930)↵    at c (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:26:22701)↵    at Object.fireWith [as resolveWith] (https://hyperstack.org/assets/application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:26:23465)"__proto__: n
application-6723ef1ebaf1619110030d62866d8066da3000f917975d4c6ce2029abbd87b9e.js:30 Uncaught n
```

**Comment by barriehadfield** [comment]
Thank you @SampsonCrowley I fixed this now, looks like they changed their API. SOrry to take so long over the fix! Thanks for raising it THOUGH.
